"""updated_notifications_for_users

Revision ID: 0a1b15d94baa
Revises: 4cada17b96f6
Create Date: 2026-06-04 09:59:08.658032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a1b15d94baa'
down_revision: Union[str, Sequence[str], None] = '4cada17b96f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('notifications', 'item_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notifications', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('notifications', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('notifications', 'item_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('notifications', 'user_id')
    # ### end Alembic commands ###
