"""added_activity_opening_hours

Revision ID: 2e0d231eddba
Revises: 18a9f82fa9bb
Create Date: 2026-05-25 10:05:55.879359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0d231eddba'
down_revision: Union[str, Sequence[str], None] = '18a9f82fa9bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_items', sa.Column('opening_days', sa.String(), nullable=True))
    op.add_column('platform_items', sa.Column('opening_hours', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_items', 'opening_hours')
    op.drop_column('platform_items', 'opening_days')
    # ### end Alembic commands ###
