"""added_saved_items_and_geospatial

Revision ID: 4380a1c85e8a
Revises: 426112b0c26d
Create Date: 2026-06-02 12:45:50.714697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4380a1c85e8a'
down_revision: Union[str, Sequence[str], None] = '426112b0c26d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['platform_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_items_id'), 'saved_items', ['id'], unique=False)
    op.add_column('platform_items', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('platform_items', sa.Column('lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_items', 'lng')
    op.drop_column('platform_items', 'lat')
    op.drop_index(op.f('ix_saved_items_id'), table_name='saved_items')
    op.drop_table('saved_items')
    # ### end Alembic commands ###
