"""added_json_tags_to_platform_items

Revision ID: 4737b0f329f8
Revises: 2e0d231eddba
Create Date: 2026-05-25 10:17:42.301027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4737b0f329f8'
down_revision: Union[str, Sequence[str], None] = '2e0d231eddba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_items', sa.Column('sub_categories', sa.JSON(), nullable=True))
    op.add_column('platform_items', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_items', 'tags')
    op.drop_column('platform_items', 'sub_categories')
    # ### end Alembic commands ###
