"""added_email_verification

Revision ID: 4bff37ec7ee5
Revises: 508115664643
Create Date: 2026-06-12 11:21:13.268844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bff37ec7ee5'
down_revision: Union[str, Sequence[str], None] = '508115664643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp_code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_otps_email'), 'email_verification_otps', ['email'], unique=False)
    op.create_index(op.f('ix_email_verification_otps_id'), 'email_verification_otps', ['id'], unique=False)
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_email_verified')
    op.drop_index(op.f('ix_email_verification_otps_id'), table_name='email_verification_otps')
    op.drop_index(op.f('ix_email_verification_otps_email'), table_name='email_verification_otps')
    op.drop_table('email_verification_otps')
    # ### end Alembic commands ###
