"""added_gift_lists_system

Revision ID: 4cada17b96f6
Revises: a5440ede4537
Create Date: 2026-06-03 15:30:56.252675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cada17b96f6'
down_revision: Union[str, Sequence[str], None] = 'a5440ede4537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_gift_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_gift_lists_id'), 'user_gift_lists', ['id'], unique=False)
    op.add_column('saved_items', sa.Column('gift_list_id', sa.Integer(), nullable=True))
    op.alter_column('saved_items', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(None, 'saved_items', 'user_gift_lists', ['gift_list_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saved_items', type_='foreignkey')
    op.alter_column('saved_items', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('saved_items', 'gift_list_id')
    op.drop_index(op.f('ix_user_gift_lists_id'), table_name='user_gift_lists')
    op.drop_table('user_gift_lists')
    # ### end Alembic commands ###
