"""added_admin_dashboard_models

Revision ID: 4dc9bd6d2312
Revises: e2e282acd815
Create Date: 2026-05-24 11:58:44.572334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc9bd6d2312'
down_revision: Union[str, Sequence[str], None] = 'e2e282acd815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_plan', sa.String(), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('join_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'join_date')
    op.drop_column('users', 'status')
    op.drop_column('users', 'subscription_plan')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
