"""refined_gift_list_logic

Revision ID: 6283338e0ca3
Revises: 0a1b15d94baa
Create Date: 2026-06-05 14:37:29.112316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6283338e0ca3'
down_revision: Union[str, Sequence[str], None] = '0a1b15d94baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_gift_lists', sa.Column('occasion', sa.String(), nullable=True))
    op.add_column('user_gift_lists', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('user_gift_lists', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_gift_lists', 'updated_at')
    op.drop_column('user_gift_lists', 'description')
    op.drop_column('user_gift_lists', 'occasion')
    # ### end Alembic commands ###
