"""added_image_url_to_gift_lists

Revision ID: e1132fca63d7
Revises: taxonomy_images_001
Create Date: 2026-06-22 14:37:51.925428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1132fca63d7'
down_revision: Union[str, Sequence[str], None] = 'taxonomy_images_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_gift_lists', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_gift_lists', 'image_url')
    # ### end Alembic commands ###
